### ISSUE TITLE
登录界面优化

### ISSUE THREAD

**Issue by JackWhuer** [NovaShang/tododo#1]
登录界面较为简洁，动画切换也挺好。不过个人觉得右边的滚动条略微尴尬，建议取消。如果能有时间，可以将登录及注册界面做成目前较为通用的界面，效果更好些。
![image](https://user-images.githubusercontent.com/30594452/28775809-85e64c9e-7626-11e7-9f68-567ff34c9478.png)

**Comment by NovaShang** [comment]
出现滚动条为BUG，已修复。页面布局暂不修改。
