### ISSUE TITLE
任务时间属性显示

### ISSUE THREAD

**Issue by JackWhuer** [NovaShang/tododo#3]
每个任务条缩略信息中可浓缩包含：重要性、标签、任务名称、任务时间，可为每条都添加显示任务时间
![image](https://user-images.githubusercontent.com/30594452/28776350-da6437fc-7628-11e7-8a0f-309a59362d19.png)

**Comment by NovaShang** [comment]
对于有设置Deadline的任务会显示日期，未过期为蓝色，已过期为红色。
